// demo-svelte/app/Menu.svelte
<style>
</style>

<page>
    <actionBar title="Svelte Demo" />
    <scrollView>
        <stackLayout>
            {#each demos as demo}
                <button
                    text={demo.name}
                    on:tap={() => {
                        goToDemo(demo.component);
                    }} />
            {/each}
        </stackLayout>
    </scrollView>
</page>

<script lang="typescript">
    import { navigate } from 'svelte-native';
    import { onMount } from 'svelte';
    import { demos } from '../../demo-snippets/svelte/install';
    function goToDemo(component) {
        navigate({
            page: component,
            animated: true,
            transition: {
                name: 'slideLeft',
                duration: 200,
                curve: 'ease'
            }
        });
    }
    onMount(() => {
        if (demoRedirect) {
            const Demo = demos.find(({ path }) => path === demoRedirect);
            if (Demo) {
                setTimeout(() => {
                    navigate({
                        page: Demo.component,
                        animated: false
                    });
                }, 0);
            }
        }
    });
</script>

// demo-ng/src/app/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';
import { demos } from '../../../../demo-snippets/ng/install.module';

@Component({
    selector: 'ns-menu',
    templateUrl: './menu.component.html'
})

export class MenuComponent implements OnInit {
    demos = demos;
    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {
        if (demoRedirect) {
            const Demo = demos.find(({ path }) => path === demoRedirect);
            if (Demo) {
                this.router.navigate([Demo.path]);
            }
        }
    }

    goToDemo(component: string): void {
        this.router.navigate([component], {
            animated: true,
            transition: {
                name: 'slideLeft',
                duration: 200,
                curve: 'ease'
            }
        });
    }
}


<ActionBar title="Angular Demo"></ActionBar>

<ScrollView>
    <StackLayout>
        <StackLayout *ngFor="let demo of demos">
            <Button text="{{ demo.name }}" (tap)="goToDemo(demo.path)"></Button>
        </StackLayout>
    </StackLayout>
</ScrollView>
