// demo-vue/app/components/Menu.vue
<template>
    <Page>
        <ActionBar>
            <Label text="Vue.js Demo" />
        </ActionBar>

        <ScrollView>
            <StackLayout>
                <StackLayout v-for="demo in demos" :key="demo.name">
                    <Button :text="demo.name" @tap="goToDemo(demo.component)" />
                </StackLayout>
            </StackLayout>
        </ScrollView>
    </Page>
</template>

<script lang="ts">
import { demos } from '../../../demo-snippets/vue/install'
declare const demoRedirect: string;

export default {
    data() {
        return {
            demos
        };
    },
    mounted() {
        if (demoRedirect) {
            const Demo = demos.find(({ path }) => path === demoRedirect);
            if (Demo) {
                this.$navigateTo(Demo.component, {
                    animated: false
                });
            }
        }
    },
    methods: {
        goToDemo(component) {
            this.$navigateTo(component, {
                animated: true,
                transition: {
                    name: 'slideLeft',
                    duration: 200,
                    curve: 'ease'
                }
            });
        }
    }
};
</script>

// demo-svelte/app/Menu.svelte
<style>
</style>

<page>
    <actionBar title="Svelte Demo" />
    <scrollView>
        <stackLayout>
            {#each demos as demo}
                <button
                    text={demo.name}
                    on:tap={() => {
                        goToDemo(demo.component);
                    }} />
            {/each}
        </stackLayout>
    </scrollView>
</page>

<script lang="typescript">
    import { navigate } from 'svelte-native';
    import { onMount } from 'svelte';
    import { demos } from '../../demo-snippets/svelte/install';
    function goToDemo(component) {
        navigate({
            page: component,
            animated: true,
            transition: {
                name: 'slideLeft',
                duration: 200,
                curve: 'ease'
            }
        });
    }
    onMount(() => {
        if (demoRedirect) {
            const Demo = demos.find(({ path }) => path === demoRedirect);
            if (Demo) {
                setTimeout(() => {
                    navigate({
                        page: Demo.component,
                        animated: false
                    });
                }, 0);
            }
        }
    });
</script>
