// demo-react/src/components/Menu.tsx
import * as React from 'react';
import { RouteProp } from '@react-navigation/core';
import { FrameNavigationProp } from 'react-nativescript-navigation';
import { MainStackParamList } from './NavigationParamList';

import { demos } from '../../../demo-snippets/react/install';
interface MenuProps {
    route: RouteProp<MainStackParamList, 'menu'>;
    navigation: FrameNavigationProp<MainStackParamList, 'menu'>;
}

declare const demoRedirect: string;

export function Menu({ navigation }: MenuProps) {
    function goToDemo(component) {
        navigation.navigate(component);
    }

    if (demoRedirect) {
        const Demo = demos.find(({ path }) => path === demoRedirect);
        if (Demo) {
            setTimeout(() => {
                // @ts-ignore
                navigation.navigate(Demo.path);
            }, 0);
        }
    }

    return (
        <scrollView>
            <stackLayout>
                {demos.map((demo) => (
                    <button
                        key={demo.name}
                        onTap={() => {
                            goToDemo(demo.path);
                        }}
                    >
                        {demo.name}
                    </button>
                ))}
            </stackLayout>
        </scrollView>
    );
}

// demo-vue/app/components/Menu.vue
<template>
    <Page>
        <ActionBar>
            <Label text="Vue.js Demo" />
        </ActionBar>

        <ScrollView>
            <StackLayout>
                <StackLayout v-for="demo in demos" :key="demo.name">
                    <Button :text="demo.name" @tap="goToDemo(demo.component)" />
                </StackLayout>
            </StackLayout>
        </ScrollView>
    </Page>
</template>

<script lang="ts">
import { demos } from '../../../demo-snippets/vue/install'
declare const demoRedirect: string;

export default {
    data() {
        return {
            demos
        };
    },
    mounted() {
        if (demoRedirect) {
            const Demo = demos.find(({ path }) => path === demoRedirect);
            if (Demo) {
                this.$navigateTo(Demo.component, {
                    animated: false
                });
            }
        }
    },
    methods: {
        goToDemo(component) {
            this.$navigateTo(component, {
                animated: true,
                transition: {
                    name: 'slideLeft',
                    duration: 200,
                    curve: 'ease'
                }
            });
        }
    }
};
</script>
